# Dependabot will run on day 6 of each month at 01:31 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "31 1 6 * *"
    open-pull-requests-limit: 20
    assignees:
      - "BenAhrdt"
    versioning-strategy: "increase"
